[package]
name = "text-to-audibook"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.5"
anyhow = "1.0.98"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
toml = "0.8.19"